mmap_load_path: data/mmap/Y_d1_2692_d2_3548_d3_1_order_C_frames_1788.mmap
cnmfe_save_path: data/cnmfe/Y-corr85-pnr12.hdf5

params:
  data:
    fr: 10
    decay_time: 1.5
    dxy: [2.5, 2.5]
  patch:
    rf: 40
    stride: 20
    only_init: true
    nb_patch: 0
    low_rank_background: null
    del_duplicates: true
  init:
    method_init: corr_pnr
    K: null
    gSig: [3, 3]
    gSiz: [7, 7]
    ssub: 1
    tsub: 1
    nb: 0
    min_corr: 0.85
    min_pnr: 12
    normalize_init: false
    center_psf: true
    ssub_B: 1
    ring_size_factor: 1.4
  preprocess:
    p: 2
    n_pixels_per_process: null
  spatial:
    update_background_components: true
  temporal:
    p: 2
    method_deconvolution: oasis
  merging:
    merge_thr: 0.7
    merge_parallel: true
